/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.irods.jargon.ga4gh.dos.api;


import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

import org.irods.jargon.ga4gh.dos.model.AccessURL;
import org.irods.jargon.ga4gh.dos.model.DrsObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-06-13T12:08:45.878Z[GMT]")
@Validated
public interface ObjectsApi {

    @Operation(summary = "Get a URL for fetching bytes", description = "Returns a URL that can be used to fetch the bytes of a `DrsObject`. This method only needs to be called when using an `AccessMethod` that contains an `access_id` (e.g., for servers that use signed URLs for fetching object bytes).", security = {
        @SecurityRequirement(name = "BasicAuth"),
@SecurityRequirement(name = "BearerAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `AccessURL` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccessURL.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}/access/{access_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AccessURL> getAccessURL(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.PATH, description = "An `access_id` from the `access_methods` list of a `DrsObject`", required=true, schema=@Schema()) @PathVariable("access_id") String accessId);


    @Operation(summary = "Get info about a DrsObject.", description = "Returns object metadata, and a list of access methods that can be used to fetch object bytes.", security = {
        @SecurityRequirement(name = "BasicAuth"),
@SecurityRequirement(name = "BearerAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `DrsObject` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DrsObject.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `DrsObject` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<DrsObject> getObject(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.QUERY, description = "If false and the object_id refers to a bundle, then the ContentsObject array contains only those objects directly contained in the bundle. That is, if the bundle contains other bundles, those other bundles are not recursively included in the result. If true and the object_id refers to a bundle, then the entire set of objects in the bundle is expanded. That is, if the bundle contains aother bundles, then those other bundles are recursively expanded and included in the result. Recursion continues through the entire sub-tree of the bundle. If the object_id refers to a blob, then the query parameter is ignored." ,schema=@Schema()) @Valid @RequestParam(value = "expand", required = false) Boolean expand);


    @Operation(summary = "Get a URL for fetching bytes through POST'ing a Passport", description = "Returns a URL that can be used to fetch the bytes of a `DrsObject`. This method only needs to be called when using an `AccessMethod` that contains an `access_id` (e.g., for servers that use signed URLs for fetching object bytes). Method is a POST to accomodate a JWT GA4GH Passport sent in the formData in order to authorize access.", security = {
        @SecurityRequirement(name = "PassportAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `AccessURL` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccessURL.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}/access/{access_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<AccessURL> postAccessURL(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.PATH, description = "An `access_id` from the `access_methods` list of a `DrsObject`", required=true, schema=@Schema()) @PathVariable("access_id") String accessId, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Object body);


    @Operation(summary = "Get info about a DrsObject through POST'ing a Passport.", description = "Returns object metadata, and a list of access methods that can be used to fetch object bytes. Method is a POST to accomodate a JWT GA4GH Passport sent in the formData in order to authorize access.", security = {
        @SecurityRequirement(name = "PassportAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `DrsObject` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DrsObject.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<DrsObject> postObject(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Object body);

}

