/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.irods.jargon.ga4gh.dos.api;

import org.irods.jargon.ga4gh.dos.model.AccessURL;
import org.irods.jargon.ga4gh.dos.model.DrsObject;
import org.irods.jargon.ga4gh.dos.model.Error;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-06-22T12:15:59.889Z[GMT]")
@Validated
public interface ObjectsApi {

    Logger log = LoggerFactory.getLogger(ObjectsApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Get a URL for fetching bytes", description = "Returns a URL that can be used to fetch the bytes of a `DrsObject`. This method only needs to be called when using an `AccessMethod` that contains an `access_id` (e.g., for servers that use signed URLs for fetching object bytes).", security = {
        @SecurityRequirement(name = "BasicAuth"),
@SecurityRequirement(name = "BearerAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `AccessURL` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccessURL.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}/access/{access_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<AccessURL> getAccessURL(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.PATH, description = "An `access_id` from the `access_methods` list of a `DrsObject`", required=true, schema=@Schema()) @PathVariable("access_id") String accessId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n  \"url\" : \"url\"\n}", AccessURL.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ObjectsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Get info about a DrsObject.", description = "Returns object metadata, and a list of access methods that can be used to fetch object bytes.", security = {
        @SecurityRequirement(name = "BasicAuth"),
@SecurityRequirement(name = "BearerAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `DrsObject` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DrsObject.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `DrsObject` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<DrsObject> getObject(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.QUERY, description = "If false and the object_id refers to a bundle, then the ContentsObject array contains only those objects directly contained in the bundle. That is, if the bundle contains other bundles, those other bundles are not recursively included in the result. If true and the object_id refers to a bundle, then the entire set of objects in the bundle is expanded. That is, if the bundle contains aother bundles, then those other bundles are recursively expanded and included in the result. Recursion continues through the entire sub-tree of the bundle. If the object_id refers to a blob, then the query parameter is ignored." ,schema=@Schema()) @Valid @RequestParam(value = "expand", required = false) Boolean expand) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"checksums\" : [ {\n    \"checksum\" : \"checksum\",\n    \"type\" : \"sha-256\"\n  }, {\n    \"checksum\" : \"checksum\",\n    \"type\" : \"sha-256\"\n  } ],\n  \"created_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"updated_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"aliases\" : [ \"aliases\", \"aliases\" ],\n  \"description\" : \"description\",\n  \"self_uri\" : \"drs://drs.example.org/314159\",\n  \"version\" : \"version\",\n  \"size\" : 0,\n  \"mime_type\" : \"application/json\",\n  \"access_methods\" : [ {\n    \"access_url\" : {\n      \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n      \"url\" : \"url\"\n    },\n    \"access_id\" : \"access_id\",\n    \"type\" : \"s3\",\n    \"region\" : \"us-east-1\"\n  }, {\n    \"access_url\" : {\n      \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n      \"url\" : \"url\"\n    },\n    \"access_id\" : \"access_id\",\n    \"type\" : \"s3\",\n    \"region\" : \"us-east-1\"\n  } ],\n  \"contents\" : [ {\n    \"contents\" : [ null, null ],\n    \"name\" : \"name\",\n    \"id\" : \"id\",\n    \"drs_uri\" : \"drs://drs.example.org/314159\"\n  }, {\n    \"contents\" : [ null, null ],\n    \"name\" : \"name\",\n    \"id\" : \"id\",\n    \"drs_uri\" : \"drs://drs.example.org/314159\"\n  } ],\n  \"name\" : \"name\",\n  \"id\" : \"id\"\n}", DrsObject.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ObjectsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Get a URL for fetching bytes through POST'ing a Passport", description = "Returns a URL that can be used to fetch the bytes of a `DrsObject`. This method only needs to be called when using an `AccessMethod` that contains an `access_id` (e.g., for servers that use signed URLs for fetching object bytes). Method is a POST to accomodate a JWT GA4GH Passport sent in the formData in order to authorize access.", security = {
        @SecurityRequirement(name = "PassportAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `AccessURL` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccessURL.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}/access/{access_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<AccessURL> postAccessURL(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.PATH, description = "An `access_id` from the `access_methods` list of a `DrsObject`", required=true, schema=@Schema()) @PathVariable("access_id") String accessId, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Object body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n  \"url\" : \"url\"\n}", AccessURL.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ObjectsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Get info about a DrsObject through POST'ing a Passport.", description = "Returns object metadata, and a list of access methods that can be used to fetch object bytes. Method is a POST to accomodate a JWT GA4GH Passport sent in the formData in order to authorize access.", security = {
        @SecurityRequirement(name = "PassportAuth")    }, tags={ "Objects" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The `DrsObject` was found successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DrsObject.class))),
        
        @ApiResponse(responseCode = "202", description = "The operation is delayed and will continue asynchronously. The client should retry this same request after the delay specified by Retry-After header. "),
        
        @ApiResponse(responseCode = "400", description = "The request is malformed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "401", description = "The request is unauthorized.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "403", description = "The requester is not authorized to perform this action.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "The requested `AccessURL` wasn't found.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/objects/{object_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<DrsObject> postObject(@Parameter(in = ParameterIn.PATH, description = "`DrsObject` identifier", required=true, schema=@Schema()) @PathVariable("object_id") String objectId, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Object body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"checksums\" : [ {\n    \"checksum\" : \"checksum\",\n    \"type\" : \"sha-256\"\n  }, {\n    \"checksum\" : \"checksum\",\n    \"type\" : \"sha-256\"\n  } ],\n  \"created_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"updated_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"aliases\" : [ \"aliases\", \"aliases\" ],\n  \"description\" : \"description\",\n  \"self_uri\" : \"drs://drs.example.org/314159\",\n  \"version\" : \"version\",\n  \"size\" : 0,\n  \"mime_type\" : \"application/json\",\n  \"access_methods\" : [ {\n    \"access_url\" : {\n      \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n      \"url\" : \"url\"\n    },\n    \"access_id\" : \"access_id\",\n    \"type\" : \"s3\",\n    \"region\" : \"us-east-1\"\n  }, {\n    \"access_url\" : {\n      \"headers\" : \"Authorization: Basic Z2E0Z2g6ZHJz\",\n      \"url\" : \"url\"\n    },\n    \"access_id\" : \"access_id\",\n    \"type\" : \"s3\",\n    \"region\" : \"us-east-1\"\n  } ],\n  \"contents\" : [ {\n    \"contents\" : [ null, null ],\n    \"name\" : \"name\",\n    \"id\" : \"id\",\n    \"drs_uri\" : \"drs://drs.example.org/314159\"\n  }, {\n    \"contents\" : [ null, null ],\n    \"name\" : \"name\",\n    \"id\" : \"id\",\n    \"drs_uri\" : \"drs://drs.example.org/314159\"\n  } ],\n  \"name\" : \"name\",\n  \"id\" : \"id\"\n}", DrsObject.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ObjectsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

